# llm:
#   type: openrouter
#   models:
#     openrouter: "openai/gpt-4o"
#     openai: Null
#     anthropic: Null
#   api_keys:
#     openrouter: ""
#     openai: ""
#     anthropic: ""
#   temperature: 0.7

# benchmark:
#   checkpoint: "checkpoints"
#   verbose: true
#   output_pattern: "results/{dataset_name}_{model}.json"



llm:
  type: "deepseek"
  models:
    deepseek: "deepseek-reasoner"
  temperature: 0.7
  api_keys:
    deepseek: ""

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}.json"

